# version: '3.8'
services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_todo_app
    ports:
      - "8000:8000"
    # volumes:
    #   - ./www:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      LOG_LEVEL: debug
      APP_URL: http://localhost:8000
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: francis
      DB_PASSWORD: Admin1234
      DB_CONNECTION: mysql
      DB_PORT: 3306
      APP_KEY: ${APP_KEY}
    depends_on:
      db:
        condition: service_healthy
    user: "www-data"

  db:
    image: mysql:5.7
    container_name: php_todo_db
    environment:
      MYSQL_ROOT_PASSWORD: Super1234
      MYSQL_DATABASE: homestead
      MYSQL_USER: francis
      MYSQL_PASSWORD: Admin1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data: