# version: '3.9'
services:
  todoapp:
    build: .
    container_name: php_todo_app
    ports:
      - "8000:8000"
    volumes:
      - todo_app:/var/www
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: php_todo_db
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: francis
      MYSQL_PASSWORD: Admin1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  todo_app:
  db_data:
